// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu0kzbi9G3YkVAC_b2KURCU7G4E0zk8uc',
    appId: '1:578122947207:web:c844f99b91a65d39e83622',
    messagingSenderId: '578122947207',
    projectId: 'dissuplain-vardan-202508091657',
    authDomain: 'dissuplain-vardan-202508091657.firebaseapp.com',
    databaseURL: 'https://dissuplain-vardan-202508091657-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dissuplain-vardan-202508091657.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7hHmzCkNQbrSSdcGC2Sc9BFBZDcNUXP8',
    appId: '1:578122947207:android:c5148db7f723c731e83622',
    messagingSenderId: '578122947207',
    projectId: 'dissuplain-vardan-202508091657',
    databaseURL: 'https://dissuplain-vardan-202508091657-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dissuplain-vardan-202508091657.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU42CmWBPOOSYpQoH_qdpkcRhcTnr-PU4',
    appId: '1:578122947207:ios:38cde4975722b417e83622',
    messagingSenderId: '578122947207',
    projectId: 'dissuplain-vardan-202508091657',
    databaseURL: 'https://dissuplain-vardan-202508091657-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dissuplain-vardan-202508091657.firebasestorage.app',
    iosBundleId: 'com.example.dissuplainAppWebMobile',
  );
}
