import 'package:firebase_database/firebase_database.dart';

final databaseRef = FirebaseDatabase.instance.ref('SubAreas');

void insertsSubAreaData() async {
databaseRef.child('1').set({'regionId': '1', 'areaID': '1', 'subareaID': '1', 'subareaName': 'Lanka', 'assignedSE': 'SS-1133'});
databaseRef.child('2').set({'regionId': '1', 'areaID': '1', 'subareaID': '2', 'subareaName': 'Awaleshpur', 'assignedSE': 'SS-1133'});
databaseRef.child('3').set({'regionId': '1', 'areaID': '1', 'subareaID': '3', 'subareaName': 'Samne Ghat', 'assignedSE': 'SS-1133'});
databaseRef.child('4').set({'regionId': '1', 'areaID': '1', 'subareaID': '4', 'subareaName': 'Sundarpur', 'assignedSE': 'SS-1133'});
databaseRef.child('5').set({'regionId': '1', 'areaID': '1', 'subareaID': '5', 'subareaName': 'Nariya', 'assignedSE': 'SS-1133'});
databaseRef.child('6').set({'regionId': '1', 'areaID': '1', 'subareaID': '6', 'subareaName': 'Bajardiha', 'assignedSE': 'SS-1133'});
databaseRef.child('7').set({'regionId': '1', 'areaID': '1', 'subareaID': '7', 'subareaName': 'Phulwaria', 'assignedSE': 'SS-1133'});
databaseRef.child('8').set({'regionId': '1', 'areaID': '1', 'subareaID': '8', 'subareaName': 'Bhagwanpur', 'assignedSE': 'SS-1133'});
databaseRef.child('9').set({'regionId': '1', 'areaID': '1', 'subareaID': '9', 'subareaName': 'Khojwa', 'assignedSE': 'SS-1133'});
databaseRef.child('10').set({'regionId': '1', 'areaID': '1', 'subareaID': '10', 'subareaName': 'Assi', 'assignedSE': 'SS-1133'});
databaseRef.child('11').set({'regionId': '1', 'areaID': '1', 'subareaID': '11', 'subareaName': 'Ramapura', 'assignedSE': 'SS-1133'});
databaseRef.child('12').set({'regionId': '1', 'areaID': '1', 'subareaID': '12', 'subareaName': 'Shivala', 'assignedSE': 'SS-1133'});
databaseRef.child('13').set({'regionId': '1', 'areaID': '1', 'subareaID': '13', 'subareaName': 'Hydrabad Gate', 'assignedSE': 'SS-1133'});
databaseRef.child('14').set({'regionId': '1', 'areaID': '1', 'subareaID': '14', 'subareaName': 'Karaundhi', 'assignedSE': 'SS-1133'});
databaseRef.child('15').set({'regionId': '1', 'areaID': '1', 'subareaID': '15', 'subareaName': 'Jaitpura', 'assignedSE': 'SS-1133'});
databaseRef.child('16').set({'regionId': '1', 'areaID': '1', 'subareaID': '16', 'subareaName': 'Hasanpura', 'assignedSE': 'SS-1133'});
databaseRef.child('17').set({'regionId': '1', 'areaID': '1', 'subareaID': '17', 'subareaName': 'Shir Goverdhan', 'assignedSE': 'SS-1133'});
databaseRef.child('18').set({'regionId': '1', 'areaID': '1', 'subareaID': '18', 'subareaName': 'Bahut Road', 'assignedSE': 'SS-1133'});
databaseRef.child('19').set({'regionId': '1', 'areaID': '1', 'subareaID': '19', 'subareaName': 'Dafi', 'assignedSE': 'SS-1133'});
databaseRef.child('20').set({'regionId': '1', 'areaID': '1', 'subareaID': '20', 'subareaName': 'Nati Imli', 'assignedSE': 'SS-1133'});
databaseRef.child('21').set({'regionId': '1', 'areaID': '1', 'subareaID': '21', 'subareaName': 'Malahiya', 'assignedSE': 'SS-1133'});
databaseRef.child('22').set({'regionId': '1', 'areaID': '1', 'subareaID': '22', 'subareaName': 'Chitupur', 'assignedSE': 'SS-1133'});
databaseRef.child('23').set({'regionId': '1', 'areaID': '1', 'subareaID': '23', 'subareaName': 'Gauri Bazar, Deoria', 'assignedSE': 'SS-1133'});
databaseRef.child('24').set({'regionId': '1', 'areaID': '1', 'subareaID': '24', 'subareaName': 'BHU', 'assignedSE': 'SS-1133'});
databaseRef.child('25').set({'regionId': '1', 'areaID': '1', 'subareaID': '25', 'subareaName': 'ALAMPURA', 'assignedSE': 'SS-1133'});
databaseRef.child('26').set({'regionId': '1', 'areaID': '1', 'subareaID': '26', 'subareaName': 'Teliyana', 'assignedSE': 'SS-1133'});
databaseRef.child('27').set({'regionId': '1', 'areaID': '1', 'subareaID': '27', 'subareaName': 'Khasipuram', 'assignedSE': 'SS-1133'});
databaseRef.child('28').set({'regionId': '1', 'areaID': '1', 'subareaID': '28', 'subareaName': 'Chetganj', 'assignedSE': 'SS-1133'});
databaseRef.child('29').set({'regionId': '1', 'areaID': '1', 'subareaID': '29', 'subareaName': 'Sigra', 'assignedSE': 'SS-1133'});
databaseRef.child('30').set({'regionId': '1', 'areaID': '1', 'subareaID': '30', 'subareaName': 'Sonia', 'assignedSE': 'SS-1133'});
databaseRef.child('31').set({'regionId': '1', 'areaID': '1', 'subareaID': '31', 'subareaName': 'Mahmoorganj', 'assignedSE': 'SS-1133'});
databaseRef.child('32').set({'regionId': '1', 'areaID': '1', 'subareaID': '32', 'subareaName': 'Chunar Road', 'assignedSE': 'SS-1133'});
databaseRef.child('33').set({'regionId': '1', 'areaID': '1', 'subareaID': '33', 'subareaName': 'Lohta', 'assignedSE': 'SS-1133'});
databaseRef.child('34').set({'regionId': '1', 'areaID': '1', 'subareaID': '34', 'subareaName': 'Kandawa', 'assignedSE': 'SS-1133'});
databaseRef.child('35').set({'regionId': '1', 'areaID': '1', 'subareaID': '35', 'subareaName': 'Sidhgiribag', 'assignedSE': 'SS-1133'});
databaseRef.child('36').set({'regionId': '1', 'areaID': '1', 'subareaID': '36', 'subareaName': 'Rathyatra', 'assignedSE': 'SS-1133'});
databaseRef.child('37').set({'regionId': '1', 'areaID': '1', 'subareaID': '37', 'subareaName': 'Nai Sarak', 'assignedSE': 'SS-1133'});
databaseRef.child('38').set({'regionId': '1', 'areaID': '1', 'subareaID': '38', 'subareaName': 'Shivdaspur', 'assignedSE': 'SS-1133'});
databaseRef.child('39').set({'regionId': '1', 'areaID': '1', 'subareaID': '39', 'subareaName': 'Aurangabad', 'assignedSE': 'SS-1133'});
databaseRef.child('40').set({'regionId': '1', 'areaID': '1', 'subareaID': '40', 'subareaName': 'Bhikari Chauraha', 'assignedSE': 'SS-1133'});
databaseRef.child('41').set({'regionId': '1', 'areaID': '1', 'subareaID': '41', 'subareaName': 'Jalalipura', 'assignedSE': 'SS-1133'});
databaseRef.child('42').set({'regionId': '1', 'areaID': '1', 'subareaID': '42', 'subareaName': 'IP Mall', 'assignedSE': 'SS-1133'});
databaseRef.child('43').set({'regionId': '1', 'areaID': '1', 'subareaID': '43', 'subareaName': 'Lallapura', 'assignedSE': 'SS-1133'});
databaseRef.child('44').set({'regionId': '1', 'areaID': '1', 'subareaID': '44', 'subareaName': 'Lath Bhairav', 'assignedSE': 'SS-1133'});
databaseRef.child('45').set({'regionId': '1', 'areaID': '1', 'subareaID': '45', 'subareaName': 'Maldhaiya', 'assignedSE': 'SS-1133'});
databaseRef.child('46').set({'regionId': '1', 'areaID': '1', 'subareaID': '46', 'subareaName': 'Akhari Bypass', 'assignedSE': 'SS-1133'});
databaseRef.child('47').set({'regionId': '1', 'areaID': '1', 'subareaID': '47', 'subareaName': 'Unknown SubArea', 'assignedSE': 'SS-1133'});
databaseRef.child('48').set({'regionId': '1', 'areaID': '1', 'subareaID': '48', 'subareaName': 'Gurubag', 'assignedSE': 'SS-1133'});
databaseRef.child('49').set({'regionId': '1', 'areaID': '1', 'subareaID': '49', 'subareaName': 'Mata Kund', 'assignedSE': 'SS-1133'});
databaseRef.child('50').set({'regionId': '1', 'areaID': '1', 'subareaID': '50', 'subareaName': 'Benia Bagh', 'assignedSE': 'SS-1133'});
databaseRef.child('51').set({'regionId': '1', 'areaID': '1', 'subareaID': '51', 'subareaName': 'Paharia', 'assignedSE': 'SS-1133'});
databaseRef.child('52').set({'regionId': '1', 'areaID': '1', 'subareaID': '52', 'subareaName': 'Tilmapur', 'assignedSE': 'SS-1133'});
databaseRef.child('53').set({'regionId': '1', 'areaID': '1', 'subareaID': '53', 'subareaName': 'Ashapur', 'assignedSE': 'SS-1133'});
databaseRef.child('54').set({'regionId': '1', 'areaID': '1', 'subareaID': '54', 'subareaName': 'Bhelupur', 'assignedSE': 'SS-1133'});
databaseRef.child('55').set({'regionId': '1', 'areaID': '1', 'subareaID': '55', 'subareaName': 'Trilochan Mahadev', 'assignedSE': 'SS-1130'});
databaseRef.child('56').set({'regionId': '1', 'areaID': '1', 'subareaID': '56', 'subareaName': 'Pindra', 'assignedSE': 'SS-1133'});
databaseRef.child('57').set({'regionId': '1', 'areaID': '1', 'subareaID': '57', 'subareaName': 'Jagatganj', 'assignedSE': 'SS-1133'});
databaseRef.child('58').set({'regionId': '1', 'areaID': '1', 'subareaID': '58', 'subareaName': 'Babatpur', 'assignedSE': 'SS-1133'});
databaseRef.child('59').set({'regionId': '1', 'areaID': '1', 'subareaID': '59', 'subareaName': 'Baniyapur', 'assignedSE': 'SS-1133'});
databaseRef.child('60').set({'regionId': '1', 'areaID': '1', 'subareaID': '60', 'subareaName': 'Bhullanpur PAC', 'assignedSE': 'SS-1133'});
databaseRef.child('61').set({'regionId': '1', 'areaID': '1', 'subareaID': '61', 'subareaName': 'Lahartara', 'assignedSE': 'SS-1133'});
databaseRef.child('62').set({'regionId': '1', 'areaID': '1', 'subareaID': '62', 'subareaName': 'Nai Basti', 'assignedSE': 'SS-1133'});
databaseRef.child('63').set({'regionId': '1', 'areaID': '1', 'subareaID': '63', 'subareaName': 'Durgakund', 'assignedSE': 'SS-1133'});
databaseRef.child('64').set({'regionId': '1', 'areaID': '1', 'subareaID': '64', 'subareaName': 'Chitaipur', 'assignedSE': 'SS-1133'});
databaseRef.child('65').set({'regionId': '1', 'areaID': '1', 'subareaID': '65', 'subareaName': 'Madanpura', 'assignedSE': 'SS-1133'});
databaseRef.child('66').set({'regionId': '1', 'areaID': '1', 'subareaID': '66', 'subareaName': 'Saket Nagar', 'assignedSE': 'SS-1133'});
databaseRef.child('67').set({'regionId': '1', 'areaID': '1', 'subareaID': '67', 'subareaName': 'Suswahi', 'assignedSE': 'SS-1133'});
databaseRef.child('68').set({'regionId': '1', 'areaID': '1', 'subareaID': '68', 'subareaName': 'Sonarpura', 'assignedSE': 'SS-1133'});
databaseRef.child('69').set({'regionId': '1', 'areaID': '2', 'subareaID': '69', 'subareaName': 'Churhata', 'assignedSE': 'SS-1124'});
databaseRef.child('70').set({'regionId': '1', 'areaID': '2', 'subareaID': '70', 'subareaName': 'Sadar Hospital', 'assignedSE': 'SS-1124'});
databaseRef.child('71').set({'regionId': '1', 'areaID': '2', 'subareaID': '71', 'subareaName': 'polytechnic chauraha', 'assignedSE': 'SS-1124'});
databaseRef.child('72').set({'regionId': '1', 'areaID': '1', 'subareaID': '72', 'subareaName': 'Sankat Mochan', 'assignedSE': 'SS-1133'});
databaseRef.child('73').set({'regionId': '1', 'areaID': '1', 'subareaID': '73', 'subareaName': 'nababganj', 'assignedSE': 'SS-1133'});
databaseRef.child('74').set({'regionId': '1', 'areaID': '1', 'subareaID': '74', 'subareaName': 'Gurudham', 'assignedSE': 'SS-1133'});
databaseRef.child('75').set({'regionId': '1', 'areaID': '1', 'subareaID': '75', 'subareaName': 'Ayar Bazaar', 'assignedSE': 'SS-1133'});
databaseRef.child('76').set({'regionId': '1', 'areaID': '1', 'subareaID': '76', 'subareaName': 'Chandpur', 'assignedSE': 'SS-1133'});
databaseRef.child('77').set({'regionId': '1', 'areaID': '2', 'subareaID': '77', 'subareaName': 'Jasis Chauraha', 'assignedSE': 'SS-1124'});
databaseRef.child('78').set({'regionId': '1', 'areaID': '2', 'subareaID': '78', 'subareaName': 'Wazidpur', 'assignedSE': 'SS-1124'});
databaseRef.child('79').set({'regionId': '1', 'areaID': '2', 'subareaID': '79', 'subareaName': 'Harbanspur', 'assignedSE': 'SS-1124'});
databaseRef.child('80').set({'regionId': '1', 'areaID': '2', 'subareaID': '80', 'subareaName': 'Jaunpur', 'assignedSE': 'SS-1124'});
databaseRef.child('81').set({'regionId': '1', 'areaID': '1', 'subareaID': '81', 'subareaName': 'Machali Shahar', 'assignedSE': 'SS-1133'});
databaseRef.child('82').set({'regionId': '1', 'areaID': '1', 'subareaID': '82', 'subareaName': 'Mariyahoon Road', 'assignedSE': 'SS-1133'});
databaseRef.child('83').set({'regionId': '1', 'areaID': '1', 'subareaID': '83', 'subareaName': 'Barigaibi', 'assignedSE': 'SS-1133'});
databaseRef.child('84').set({'regionId': '1', 'areaID': '1', 'subareaID': '84', 'subareaName': 'Shakundhara Pokhara', 'assignedSE': 'SS-1133'});
databaseRef.child('85').set({'regionId': '1', 'areaID': '2', 'subareaID': '85', 'subareaName': 'Kotwali', 'assignedSE': 'SS-1124'});
databaseRef.child('86').set({'regionId': '1', 'areaID': '1', 'subareaID': '86', 'subareaName': 'Maduwadih', 'assignedSE': 'SS-1133'});
databaseRef.child('87').set({'regionId': '1', 'areaID': '1', 'subareaID': '87', 'subareaName': 'Kachhwa', 'assignedSE': 'SS-1133'});
databaseRef.child('88').set({'regionId': '1', 'areaID': '1', 'subareaID': '88', 'subareaName': 'abc', 'assignedSE': 'SS-1133'});
databaseRef.child('89').set({'regionId': '1', 'areaID': '1', 'subareaID': '89', 'subareaName': 'Rohaniya', 'assignedSE': 'SS-1133'});
databaseRef.child('90').set({'regionId': '1', 'areaID': '1', 'subareaID': '90', 'subareaName': 'Morela', 'assignedSE': 'SS-1133'});
databaseRef.child('91').set({'regionId': '1', 'areaID': '1', 'subareaID': '91', 'subareaName': 'Marui', 'assignedSE': 'SS-1133'});
databaseRef.child('92').set({'regionId': '1', 'areaID': '1', 'subareaID': '92', 'subareaName': 'Mohansarai', 'assignedSE': 'SS-1133'});
databaseRef.child('93').set({'regionId': '1', 'areaID': '1', 'subareaID': '93', 'subareaName': 'Prahalad Ghat', 'assignedSE': 'SS-1133'});
databaseRef.child('94').set({'regionId': '1', 'areaID': '1', 'subareaID': '94', 'subareaName': 'Nathupur', 'assignedSE': 'SS-1133'});
databaseRef.child('95').set({'regionId': '1', 'areaID': '1', 'subareaID': '95', 'subareaName': 'Sahavaha', 'assignedSE': 'SS-1133'});
databaseRef.child('96').set({'regionId': '1', 'areaID': '1', 'subareaID': '96', 'subareaName': 'Golgadha', 'assignedSE': 'SS-1133'});
databaseRef.child('97').set({'regionId': '1', 'areaID': '3', 'subareaID': '97', 'subareaName': 'Kachhwa', 'assignedSE': 'SS-1133'});
databaseRef.child('98').set({'regionId': '1', 'areaID': '1', 'subareaID': '98', 'subareaName': 'Chitrasenpur', 'assignedSE': 'SS-1133'});
databaseRef.child('99').set({'regionId': '1', 'areaID': '1', 'subareaID': '99', 'subareaName': 'Chaukaghat', 'assignedSE': 'SS-1133'});
databaseRef.child('100').set({'regionId': '1', 'areaID': '1', 'subareaID': '100', 'subareaName': 'Kabir Chauraha', 'assignedSE': 'SS-1133'});
databaseRef.child('101').set({'regionId': '1', 'areaID': '1', 'subareaID': '101', 'subareaName': 'Adampur', 'assignedSE': 'SS-1133'});
databaseRef.child('102').set({'regionId': '1', 'areaID': '1', 'subareaID': '102', 'subareaName': 'Daudpur', 'assignedSE': 'SS-1133'});
databaseRef.child('103').set({'regionId': '1', 'areaID': '1', 'subareaID': '103', 'subareaName': 'Kapseti', 'assignedSE': 'SS-1133'});
databaseRef.child('104').set({'regionId': '1', 'areaID': '1', 'subareaID': '104', 'subareaName': 'Bhainsa Gaon', 'assignedSE': 'SS-1133'});
databaseRef.child('105').set({'regionId': '1', 'areaID': '1', 'subareaID': '105', 'subareaName': 'Barki', 'assignedSE': 'SS-1133'});
databaseRef.child('106').set({'regionId': '1', 'areaID': '1', 'subareaID': '106', 'subareaName': 'Katka', 'assignedSE': 'SS-1133'});
databaseRef.child('107').set({'regionId': '1', 'areaID': '1', 'subareaID': '107', 'subareaName': 'Mirzamurad', 'assignedSE': 'SS-1133'});
databaseRef.child('108').set({'regionId': '1', 'areaID': '1', 'subareaID': '108', 'subareaName': 'Babu Sarai', 'assignedSE': 'SS-1133'});
databaseRef.child('109').set({'regionId': '1', 'areaID': '1', 'subareaID': '109', 'subareaName': 'Aurai', 'assignedSE': 'SS-1133'});
databaseRef.child('110').set({'regionId': '1', 'areaID': '1', 'subareaID': '110', 'subareaName': 'Basai', 'assignedSE': 'SS-1133'});
databaseRef.child('111').set({'regionId': '1', 'areaID': '1', 'subareaID': '111', 'subareaName': 'Rajatalab', 'assignedSE': 'SS-1133'});
databaseRef.child('112').set({'regionId': '1', 'areaID': '1', 'subareaID': '112', 'subareaName': 'Jamua', 'assignedSE': 'SS-1133'});
databaseRef.child('113').set({'regionId': '1', 'areaID': '1', 'subareaID': '113', 'subareaName': 'Sakalpur', 'assignedSE': 'SS-1133'});
databaseRef.child('114').set({'regionId': '1', 'areaID': '1', 'subareaID': '114', 'subareaName': 'Maidagin', 'assignedSE': 'SS-1133'});
databaseRef.child('115').set({'regionId': '1', 'areaID': '1', 'subareaID': '115', 'subareaName': 'Manpur', 'assignedSE': 'SS-1133'});
databaseRef.child('116').set({'regionId': '1', 'areaID': '4', 'subareaID': '116', 'subareaName': 'Jhawa, Bhadohi', 'assignedSE': 'SS-1124'});
databaseRef.child('117').set({'regionId': '1', 'areaID': '4', 'subareaID': '117', 'subareaName': 'Babu Sarai', 'assignedSE': 'SS-1124'});
databaseRef.child('118').set({'regionId': '1', 'areaID': '1', 'subareaID': '118', 'subareaName': 'Machodari', 'assignedSE': 'SS-1133'});
databaseRef.child('119').set({'regionId': '1', 'areaID': '1', 'subareaID': '119', 'subareaName': 'Badi Bazar', 'assignedSE': 'SS-1133'});
databaseRef.child('120').set({'regionId': '1', 'areaID': '1', 'subareaID': '120', 'subareaName': 'Bhawanipur', 'assignedSE': 'SS-1133'});
databaseRef.child('121').set({'regionId': '1', 'areaID': '1', 'subareaID': '121', 'subareaName': 'Bhartara', 'assignedSE': 'SS-1133'});
databaseRef.child('122').set({'regionId': '1', 'areaID': '1', 'subareaID': '122', 'subareaName': 'Bhadohi', 'assignedSE': 'SS-1133'});
databaseRef.child('123').set({'regionId': '1', 'areaID': '5', 'subareaID': '123', 'subareaName': 'Bhirha Bazaar Azamgarh', 'assignedSE': 'SS-1124'});
databaseRef.child('124').set({'regionId': '1', 'areaID': '1', 'subareaID': '124', 'subareaName': 'Chatti Geti', 'assignedSE': 'SS-1133'});
databaseRef.child('125').set({'regionId': '1', 'areaID': '1', 'subareaID': '125', 'subareaName': 'Rupapur', 'assignedSE': 'SS-1133'});
databaseRef.child('126').set({'regionId': '1', 'areaID': '1', 'subareaID': '126', 'subareaName': 'Jamua ', 'assignedSE': 'SS-1133'});
databaseRef.child('127').set({'regionId': '1', 'areaID': '2', 'subareaID': '127', 'subareaName': 'Aahiyarpur', 'assignedSE': 'SS-1124'});
databaseRef.child('128').set({'regionId': '1', 'areaID': '1', 'subareaID': '128', 'subareaName': 'Hridaypur', 'assignedSE': 'SS-1133'});
databaseRef.child('129').set({'regionId': '1', 'areaID': '1', 'subareaID': '129', 'subareaName': 'Adhampur', 'assignedSE': 'SS-1133'});
databaseRef.child('130').set({'regionId': '1', 'areaID': '1', 'subareaID': '130', 'subareaName': 'Hanuman Phatak', 'assignedSE': 'SS-1133'});
databaseRef.child('131').set({'regionId': '1', 'areaID': '4', 'subareaID': '131', 'subareaName': 'Ramraiya Pur', 'assignedSE': 'SS-1124'});
databaseRef.child('132').set({'regionId': '2', 'areaID': '6', 'subareaID': '132', 'subareaName': 'Ayodhya', 'assignedSE': 'SS-1124'});
databaseRef.child('133').set({'regionId': '2', 'areaID': '6', 'subareaID': '133', 'subareaName': 'Aashpur', 'assignedSE': 'SS-1124'});
databaseRef.child('134').set({'regionId': '2', 'areaID': '6', 'subareaID': '134', 'subareaName': 'Kaptanganj', 'assignedSE': 'SS-1124'});
databaseRef.child('135').set({'regionId': '2', 'areaID': '6', 'subareaID': '135', 'subareaName': 'ridganj', 'assignedSE': 'SS-1124'});
databaseRef.child('136').set({'regionId': '2', 'areaID': '6', 'subareaID': '136', 'subareaName': 'Shakti Nagar', 'assignedSE': 'SS-1124'});
databaseRef.child('137').set({'regionId': '2', 'areaID': '6', 'subareaID': '137', 'subareaName': 'Patel Nagar', 'assignedSE': 'SS-1124'});
databaseRef.child('138').set({'regionId': '1', 'areaID': '1', 'subareaID': '138', 'subareaName': 'Raja Bazar', 'assignedSE': 'SS-1130'});
databaseRef.child('139').set({'regionId': '1', 'areaID': '1', 'subareaID': '139', 'subareaName': 'Nadesar', 'assignedSE': 'SS-1130'});
databaseRef.child('140').set({'regionId': '1', 'areaID': '1', 'subareaID': '140', 'subareaName': 'Lacchipura', 'assignedSE': 'SS-1130'});
databaseRef.child('141').set({'regionId': '1', 'areaID': '1', 'subareaID': '141', 'subareaName': 'Sikarau', 'assignedSE': 'SS-1130'});
databaseRef.child('142').set({'regionId': '1', 'areaID': '1', 'subareaID': '142', 'subareaName': 'Bunkar Market', 'assignedSE': 'SS-1130'});
databaseRef.child('143').set({'regionId': '1', 'areaID': '1', 'subareaID': '143', 'subareaName': 'Tatakpur', 'assignedSE': 'SS-1130'});
databaseRef.child('144').set({'regionId': '1', 'areaID': '1', 'subareaID': '144', 'subareaName': 'Kutchry', 'assignedSE': 'SS-1130'});
databaseRef.child('145').set({'regionId': '1', 'areaID': '1', 'subareaID': '145', 'subareaName': 'Hukulganj', 'assignedSE': 'SS-1130'});
databaseRef.child('146').set({'regionId': '1', 'areaID': '1', 'subareaID': '146', 'subareaName': 'Panchoshi Road', 'assignedSE': 'SS-1130'});
databaseRef.child('147').set({'regionId': '1', 'areaID': '1', 'subareaID': '147', 'subareaName': 'Sikrauli', 'assignedSE': 'SS-1130'});
databaseRef.child('148').set({'regionId': '1', 'areaID': '1', 'subareaID': '148', 'subareaName': 'Jalaipur', 'assignedSE': 'SS-1130'});
databaseRef.child('149').set({'regionId': '1', 'areaID': '1', 'subareaID': '149', 'subareaName': 'Sarang Talab', 'assignedSE': 'SS-1130'});
databaseRef.child('150').set({'regionId': '1', 'areaID': '1', 'subareaID': '150', 'subareaName': 'Chaubeypur', 'assignedSE': 'SS-1130'});
databaseRef.child('151').set({'regionId': '1', 'areaID': '1', 'subareaID': '151', 'subareaName': 'Rauna Khurd', 'assignedSE': 'SS-1130'});
databaseRef.child('152').set({'regionId': '1', 'areaID': '1', 'subareaID': '152', 'subareaName': 'Sompur', 'assignedSE': 'SS-1130'});
databaseRef.child('153').set({'regionId': '1', 'areaID': '1', 'subareaID': '153', 'subareaName': 'Jansa', 'assignedSE': 'SS-1130'});
databaseRef.child('154').set({'regionId': '1', 'areaID': '1', 'subareaID': '154', 'subareaName': 'Sarnath', 'assignedSE': 'SS-1130'});
databaseRef.child('155').set({'regionId': '1', 'areaID': '1', 'subareaID': '155', 'subareaName': 'Rustampur', 'assignedSE': 'SS-1130'});
databaseRef.child('156').set({'regionId': '1', 'areaID': '1', 'subareaID': '156', 'subareaName': 'Umraha', 'assignedSE': 'SS-1130'});
databaseRef.child('157').set({'regionId': '1', 'areaID': '1', 'subareaID': '157', 'subareaName': 'Kadipur kala', 'assignedSE': 'SS-1130'});
databaseRef.child('158').set({'regionId': '1', 'areaID': '1', 'subareaID': '158', 'subareaName': 'SATHWA', 'assignedSE': 'SS-1130'});
databaseRef.child('159').set({'regionId': '1', 'areaID': '1', 'subareaID': '159', 'subareaName': 'GOPUR', 'assignedSE': 'SS-1130'});
databaseRef.child('160').set({'regionId': '1', 'areaID': '1', 'subareaID': '160', 'subareaName': 'Mugalsarai', 'assignedSE': 'SS-1130'});
databaseRef.child('161').set({'regionId': '1', 'areaID': '1', 'subareaID': '161', 'subareaName': 'Ordilay Bazar', 'assignedSE': 'SS-1130'});
databaseRef.child('162').set({'regionId': '1', 'areaID': '1', 'subareaID': '162', 'subareaName': 'Parao', 'assignedSE': 'SS-1130'});
databaseRef.child('163').set({'regionId': '1', 'areaID': '1', 'subareaID': '163', 'subareaName': 'Pandeypur', 'assignedSE': 'SS-1130'});
databaseRef.child('164').set({'regionId': '1', 'areaID': '7', 'subareaID': '164', 'subareaName': 'Mugalsarai', 'assignedSE': 'SS-1130'});
databaseRef.child('165').set({'regionId': '1', 'areaID': '1', 'subareaID': '165', 'subareaName': 'Bhojuveer', 'assignedSE': 'SS-1130'});
databaseRef.child('166').set({'regionId': '1', 'areaID': '1', 'subareaID': '166', 'subareaName': 'Ordily Bazar', 'assignedSE': 'SS-1130'});
databaseRef.child('167').set({'regionId': '1', 'areaID': '1', 'subareaID': '167', 'subareaName': 'Saralpur', 'assignedSE': 'SS-1130'});
databaseRef.child('168').set({'regionId': '1', 'areaID': '1', 'subareaID': '168', 'subareaName': 'Salarpur', 'assignedSE': 'SS-1130'});
databaseRef.child('169').set({'regionId': '1', 'areaID': '1', 'subareaID': '169', 'subareaName': 'Jalhupur', 'assignedSE': 'SS-1130'});
databaseRef.child('170').set({'regionId': '1', 'areaID': '1', 'subareaID': '170', 'subareaName': 'Nakki Ghat', 'assignedSE': 'SS-1130'});
databaseRef.child('171').set({'regionId': '1', 'areaID': '1', 'subareaID': '171', 'subareaName': 'Gaurakala', 'assignedSE': 'SS-1130'});
databaseRef.child('172').set({'regionId': '1', 'areaID': '1', 'subareaID': '172', 'subareaName': 'Kapildhara', 'assignedSE': 'SS-1130'});
databaseRef.child('173').set({'regionId': '1', 'areaID': '1', 'subareaID': '173', 'subareaName': 'Rasulgarh', 'assignedSE': 'SS-1130'});
databaseRef.child('174').set({'regionId': '1', 'areaID': '1', 'subareaID': '174', 'subareaName': 'Balua Road', 'assignedSE': 'SS-1130'});
databaseRef.child('175').set({'regionId': '1', 'areaID': '1', 'subareaID': '175', 'subareaName': 'Tandiya Chakvihi ', 'assignedSE': 'SS-1130'});
databaseRef.child('176').set({'regionId': '1', 'areaID': '1', 'subareaID': '176', 'subareaName': 'Punjabi Hospital', 'assignedSE': 'SS-1130'});
databaseRef.child('177').set({'regionId': '1', 'areaID': '1', 'subareaID': '177', 'subareaName': 'Cholapur', 'assignedSE': 'SS-1130'});
databaseRef.child('178').set({'regionId': '1', 'areaID': '1', 'subareaID': '178', 'subareaName': 'Dhanganj', 'assignedSE': 'SS-1130'});
databaseRef.child('179').set({'regionId': '1', 'areaID': '1', 'subareaID': '179', 'subareaName': 'Ledupur', 'assignedSE': 'SS-1130'});
databaseRef.child('180').set({'regionId': '1', 'areaID': '1', 'subareaID': '180', 'subareaName': 'Kotawa', 'assignedSE': 'SS-1130'});
databaseRef.child('181').set({'regionId': '1', 'areaID': '1', 'subareaID': '181', 'subareaName': 'Byaspur', 'assignedSE': 'SS-1130'});
databaseRef.child('182').set({'regionId': '1', 'areaID': '1', 'subareaID': '182', 'subareaName': 'Shivpur', 'assignedSE': 'SS-1130'});
databaseRef.child('183').set({'regionId': '1', 'areaID': '1', 'subareaID': '183', 'subareaName': 'Bada Gaon', 'assignedSE': 'SS-1130'});
databaseRef.child('184').set({'regionId': '1', 'areaID': '1', 'subareaID': '184', 'subareaName': 'Hathiwar', 'assignedSE': 'SS-1130'});
databaseRef.child('185').set({'regionId': '1', 'areaID': '1', 'subareaID': '185', 'subareaName': 'karkhiyao', 'assignedSE': 'SS-1130'});
databaseRef.child('186').set({'regionId': '1', 'areaID': '1', 'subareaID': '186', 'subareaName': 'Rameshwar', 'assignedSE': 'SS-1130'});
databaseRef.child('187').set({'regionId': '1', 'areaID': '1', 'subareaID': '187', 'subareaName': 'Jagdishpur', 'assignedSE': 'SS-1130'});
databaseRef.child('188').set({'regionId': '1', 'areaID': '1', 'subareaID': '188', 'subareaName': 'Pancho Shivala', 'assignedSE': 'SS-1130'});
databaseRef.child('189').set({'regionId': '1', 'areaID': '1', 'subareaID': '189', 'subareaName': 'Haraua', 'assignedSE': 'SS-1130'});
databaseRef.child('190').set({'regionId': '1', 'areaID': '1', 'subareaID': '190', 'subareaName': 'Duniyapur', 'assignedSE': 'SS-1130'});
databaseRef.child('191').set({'regionId': '1', 'areaID': '1', 'subareaID': '191', 'subareaName': 'Karkhiyaon', 'assignedSE': 'SS-1130'});
databaseRef.child('192').set({'regionId': '1', 'areaID': '1', 'subareaID': '192', 'subareaName': 'Wazidpur', 'assignedSE': 'SS-1130'});
databaseRef.child('193').set({'regionId': '1', 'areaID': '1', 'subareaID': '193', 'subareaName': 'Chiraigaon', 'assignedSE': 'SS-1130'});
databaseRef.child('194').set({'regionId': '1', 'areaID': '1', 'subareaID': '194', 'subareaName': 'Chandmari', 'assignedSE': 'SS-1130'});
databaseRef.child('195').set({'regionId': '1', 'areaID': '1', 'subareaID': '195', 'subareaName': 'Lamhi', 'assignedSE': 'SS-1130'});
databaseRef.child('196').set({'regionId': '1', 'areaID': '1', 'subareaID': '196', 'subareaName': 'Soyepur', 'assignedSE': 'SS-1130'});
databaseRef.child('197').set({'regionId': '1', 'areaID': '1', 'subareaID': '197', 'subareaName': 'Belwa Baba', 'assignedSE': 'SS-1130'});
databaseRef.child('198').set({'regionId': '1', 'areaID': '1', 'subareaID': '198', 'subareaName': 'Sindhora', 'assignedSE': 'SS-1130'});
databaseRef.child('199').set({'regionId': '1', 'areaID': '1', 'subareaID': '199', 'subareaName': 'Bada lalpur', 'assignedSE': 'SS-1130'});
databaseRef.child('200').set({'regionId': '1', 'areaID': '1', 'subareaID': '200', 'subareaName': 'Natiniyadai', 'assignedSE': 'SS-1130'});
databaseRef.child('201').set({'regionId': '1', 'areaID': '1', 'subareaID': '201', 'subareaName': 'Chitragupt Madir', 'assignedSE': 'SS-1130'});
databaseRef.child('202').set({'regionId': '1', 'areaID': '1', 'subareaID': '202', 'subareaName': 'Benipur', 'assignedSE': 'SS-1130'});
databaseRef.child('203').set({'regionId': '1', 'areaID': '1', 'subareaID': '203', 'subareaName': 'Goithaha', 'assignedSE': 'SS-1130'});
databaseRef.child('204').set({'regionId': '1', 'areaID': '2', 'subareaID': '204', 'subareaName': 'Trilochan Mahadev', 'assignedSE': 'SS-1124'});
databaseRef.child('205').set({'regionId': '1', 'areaID': '1', 'subareaID': '205', 'subareaName': 'Nataniya Dai', 'assignedSE': 'SS-1130'});
databaseRef.child('206').set({'regionId': '1', 'areaID': '1', 'subareaID': '206', 'subareaName': 'Murdaha Bazar', 'assignedSE': 'SS-1130'});
databaseRef.child('207').set({'regionId': '1', 'areaID': '1', 'subareaID': '207', 'subareaName': 'Aayar Bazar', 'assignedSE': 'SS-1130'});
databaseRef.child('208').set({'regionId': '1', 'areaID': '1', 'subareaID': '208', 'subareaName': 'Belwariya', 'assignedSE': 'SS-1130'});
databaseRef.child('209').set({'regionId': '3', 'areaID': '8', 'subareaID': '209', 'subareaName': 'Tagore Town ', 'assignedSE': 'SS-1131'});
databaseRef.child('210').set({'regionId': '3', 'areaID': '8', 'subareaID': '210', 'subareaName': 'Balson', 'assignedSE': 'SS-1131'});
databaseRef.child('211').set({'regionId': '3', 'areaID': '8', 'subareaID': '211', 'subareaName': 'George Town', 'assignedSE': 'SS-1131'});
databaseRef.child('212').set({'regionId': '3', 'areaID': '8', 'subareaID': '212', 'subareaName': 'Lowther Road', 'assignedSE': 'SS-1131'});
databaseRef.child('213').set({'regionId': '3', 'areaID': '8', 'subareaID': '213', 'subareaName': 'Darbhanga Colony', 'assignedSE': 'SS-1131'});
databaseRef.child('214').set({'regionId': '3', 'areaID': '8', 'subareaID': '214', 'subareaName': 'Chintamani Road', 'assignedSE': 'SS-1131'});
databaseRef.child('215').set({'regionId': '3', 'areaID': '8', 'subareaID': '215', 'subareaName': 'Hashimpur', 'assignedSE': 'SS-1131'});
databaseRef.child('216').set({'regionId': '3', 'areaID': '8', 'subareaID': '216', 'subareaName': 'Allenganj', 'assignedSE': 'SS-1131'});
databaseRef.child('217').set({'regionId': '3', 'areaID': '8', 'subareaID': '217', 'subareaName': 'Jha Marg', 'assignedSE': 'SS-1131'});
databaseRef.child('218').set({'regionId': '3', 'areaID': '8', 'subareaID': '218', 'subareaName': 'Park Road', 'assignedSE': 'SS-1131'});
databaseRef.child('219').set({'regionId': '3', 'areaID': '8', 'subareaID': '219', 'subareaName': 'Jawahar Lal Nehru Road', 'assignedSE': 'SS-1131'});
databaseRef.child('220').set({'regionId': '3', 'areaID': '8', 'subareaID': '220', 'subareaName': 'Panna Lal Road', 'assignedSE': 'SS-1131'});
databaseRef.child('221').set({'regionId': '3', 'areaID': '8', 'subareaID': '221', 'subareaName': 'Church Lane', 'assignedSE': 'SS-1131'});
databaseRef.child('222').set({'regionId': '3', 'areaID': '8', 'subareaID': '222', 'subareaName': 'Colonelganj', 'assignedSE': 'SS-1131'});
databaseRef.child('223').set({'regionId': '3', 'areaID': '8', 'subareaID': '223', 'subareaName': 'Basu Road', 'assignedSE': 'SS-1131'});
databaseRef.child('224').set({'regionId': '3', 'areaID': '8', 'subareaID': '224', 'subareaName': 'Naini', 'assignedSE': 'SS-1131'});
databaseRef.child('225').set({'regionId': '3', 'areaID': '8', 'subareaID': '225', 'subareaName': 'Bai ka Bagh', 'assignedSE': 'SS-1131'});
databaseRef.child('226').set({'regionId': '3', 'areaID': '8', 'subareaID': '226', 'subareaName': 'Behrana', 'assignedSE': 'SS-1131'});
databaseRef.child('227').set({'regionId': '3', 'areaID': '8', 'subareaID': '227', 'subareaName': 'Rambagh', 'assignedSE': 'SS-1131'});
databaseRef.child('228').set({'regionId': '3', 'areaID': '8', 'subareaID': '228', 'subareaName': 'Sohbatiyabagh', 'assignedSE': 'SS-1131'});
databaseRef.child('229').set({'regionId': '3', 'areaID': '8', 'subareaID': '229', 'subareaName': 'Katju Road', 'assignedSE': 'SS-1131'});
databaseRef.child('230').set({'regionId': '3', 'areaID': '8', 'subareaID': '230', 'subareaName': 'Kydgunj', 'assignedSE': 'SS-1131'});
databaseRef.child('231').set({'regionId': '3', 'areaID': '8', 'subareaID': '231', 'subareaName': 'Katghar Muthiganj', 'assignedSE': 'SS-1131'});
databaseRef.child('232').set({'regionId': '3', 'areaID': '8', 'subareaID': '232', 'subareaName': 'Sammelan Marg', 'assignedSE': 'SS-1131'});
databaseRef.child('233').set({'regionId': '3', 'areaID': '8', 'subareaID': '233', 'subareaName': 'Mutthiganj', 'assignedSE': 'SS-1131'});
databaseRef.child('234').set({'regionId': '3', 'areaID': '8', 'subareaID': '234', 'subareaName': 'Gulati Marg', 'assignedSE': 'SS-1131'});
databaseRef.child('235').set({'regionId': '3', 'areaID': '8', 'subareaID': '235', 'subareaName': 'Kothaparcha', 'assignedSE': 'SS-1131'});
databaseRef.child('236').set({'regionId': '3', 'areaID': '8', 'subareaID': '236', 'subareaName': 'TulaRambagh', 'assignedSE': 'SS-1131'});
databaseRef.child('237').set({'regionId': '3', 'areaID': '8', 'subareaID': '237', 'subareaName': 'Chandralok', 'assignedSE': 'SS-1131'});
databaseRef.child('238').set({'regionId': '3', 'areaID': '8', 'subareaID': '238', 'subareaName': 'KP Kakkar Road', 'assignedSE': 'SS-1131'});
databaseRef.child('239').set({'regionId': '3', 'areaID': '8', 'subareaID': '239', 'subareaName': 'Madhwapur', 'assignedSE': 'SS-1131'});
databaseRef.child('240').set({'regionId': '3', 'areaID': '8', 'subareaID': '240', 'subareaName': 'Bairhana', 'assignedSE': 'SS-1131'});
databaseRef.child('241').set({'regionId': '3', 'areaID': '8', 'subareaID': '241', 'subareaName': 'Baluaghat', 'assignedSE': 'SS-1131'});
databaseRef.child('242').set({'regionId': '3', 'areaID': '8', 'subareaID': '242', 'subareaName': 'Himmatganj Prem Nagar', 'assignedSE': 'SS-1131'});
databaseRef.child('243').set({'regionId': '3', 'areaID': '8', 'subareaID': '243', 'subareaName': 'MG Marg', 'assignedSE': 'SS-1131'});
databaseRef.child('244').set({'regionId': '3', 'areaID': '8', 'subareaID': '244', 'subareaName': 'Stanely Road', 'assignedSE': 'SS-1131'});
databaseRef.child('245').set({'regionId': '3', 'areaID': '8', 'subareaID': '245', 'subareaName': 'Civil Lines', 'assignedSE': 'SS-1131'});
databaseRef.child('246').set({'regionId': '3', 'areaID': '8', 'subareaID': '246', 'subareaName': 'Drummond Road', 'assignedSE': 'SS-1131'});
databaseRef.child('247').set({'regionId': '3', 'areaID': '8', 'subareaID': '247', 'subareaName': 'Lohia Marg', 'assignedSE': 'SS-1131'});
databaseRef.child('248').set({'regionId': '3', 'areaID': '8', 'subareaID': '248', 'subareaName': 'Thomhill Road', 'assignedSE': 'SS-1131'});
databaseRef.child('249').set({'regionId': '3', 'areaID': '8', 'subareaID': '249', 'subareaName': 'Hastings Road', 'assignedSE': 'SS-1131'});
databaseRef.child('250').set({'regionId': '3', 'areaID': '8', 'subareaID': '250', 'subareaName': 'Elgin Road', 'assignedSE': 'SS-1131'});
databaseRef.child('251').set({'regionId': '3', 'areaID': '8', 'subareaID': '251', 'subareaName': 'Clive Road', 'assignedSE': 'SS-1131'});
databaseRef.child('252').set({'regionId': '3', 'areaID': '8', 'subareaID': '252', 'subareaName': 'Ponappa Road', 'assignedSE': 'SS-1131'});
databaseRef.child('253').set({'regionId': '3', 'areaID': '8', 'subareaID': '253', 'subareaName': 'Circular Road', 'assignedSE': 'SS-1131'});
databaseRef.child('254').set({'regionId': '3', 'areaID': '8', 'subareaID': '254', 'subareaName': 'Mayo Road', 'assignedSE': 'SS-1131'});
databaseRef.child('255').set({'regionId': '3', 'areaID': '8', 'subareaID': '255', 'subareaName': 'Maur Road', 'assignedSE': 'SS-1131'});
databaseRef.child('256').set({'regionId': '3', 'areaID': '8', 'subareaID': '256', 'subareaName': 'Auckland Road', 'assignedSE': 'SS-1131'});
databaseRef.child('257').set({'regionId': '3', 'areaID': '8', 'subareaID': '257', 'subareaName': 'Yusuf Road', 'assignedSE': 'SS-1131'});
databaseRef.child('258').set({'regionId': '3', 'areaID': '8', 'subareaID': '258', 'subareaName': 'Tashkant Marg', 'assignedSE': 'SS-1131'});
databaseRef.child('259').set({'regionId': '3', 'areaID': '8', 'subareaID': '259', 'subareaName': 'Kasturba Gandhi Marg', 'assignedSE': 'SS-1131'});
databaseRef.child('260').set({'regionId': '3', 'areaID': '8', 'subareaID': '260', 'subareaName': 'Shastri Marg', 'assignedSE': 'SS-1131'});
databaseRef.child('261').set({'regionId': '3', 'areaID': '8', 'subareaID': '261', 'subareaName': 'Hamilton Road', 'assignedSE': 'SS-1131'});
databaseRef.child('262').set({'regionId': '3', 'areaID': '8', 'subareaID': '262', 'subareaName': 'Nyaya Marg', 'assignedSE': 'SS-1131'});
databaseRef.child('263').set({'regionId': '3', 'areaID': '8', 'subareaID': '263', 'subareaName': 'Rajapur', 'assignedSE': 'SS-1131'});
databaseRef.child('264').set({'regionId': '3', 'areaID': '8', 'subareaID': '264', 'subareaName': 'Muir Road', 'assignedSE': 'SS-1131'});
databaseRef.child('265').set({'regionId': '3', 'areaID': '8', 'subareaID': '265', 'subareaName': 'Sarojini Naidu Marg', 'assignedSE': 'SS-1131'});
databaseRef.child('266').set({'regionId': '3', 'areaID': '8', 'subareaID': '266', 'subareaName': 'Bank Road', 'assignedSE': 'SS-1131'});
databaseRef.child('267').set({'regionId': '3', 'areaID': '8', 'subareaID': '267', 'subareaName': 'Prayag Street', 'assignedSE': 'SS-1131'});
databaseRef.child('268').set({'regionId': '3', 'areaID': '8', 'subareaID': '268', 'subareaName': 'Minhajpur', 'assignedSE': 'SS-1131'});
databaseRef.child('269').set({'regionId': '3', 'areaID': '8', 'subareaID': '269', 'subareaName': 'Ashok Nagar', 'assignedSE': 'SS-1131'});
databaseRef.child('270').set({'regionId': '3', 'areaID': '8', 'subareaID': '270', 'subareaName': 'Patrakar Colony', 'assignedSE': 'SS-1131'});
databaseRef.child('271').set({'regionId': '3', 'areaID': '8', 'subareaID': '271', 'subareaName': 'Kuchahri', 'assignedSE': 'SS-1131'});
databaseRef.child('272').set({'regionId': '3', 'areaID': '8', 'subareaID': '272', 'subareaName': 'Dwarikpuri Muir Road', 'assignedSE': 'SS-1131'});
databaseRef.child('273').set({'regionId': '3', 'areaID': '8', 'subareaID': '273', 'subareaName': 'Bund Road', 'assignedSE': 'SS-1131'});
databaseRef.child('274').set({'regionId': '3', 'areaID': '8', 'subareaID': '274', 'subareaName': 'Chatham Lines Hawaghar', 'assignedSE': 'SS-1131'});
databaseRef.child('275').set({'regionId': '3', 'areaID': '8', 'subareaID': '275', 'subareaName': 'Muirabad', 'assignedSE': 'SS-1131'});
databaseRef.child('276').set({'regionId': '3', 'areaID': '8', 'subareaID': '276', 'subareaName': 'Bhawapur Sadar', 'assignedSE': 'SS-1131'});
databaseRef.child('277').set({'regionId': '3', 'areaID': '8', 'subareaID': '277', 'subareaName': 'Attarsuiya', 'assignedSE': 'SS-1131'});
databaseRef.child('278').set({'regionId': '3', 'areaID': '8', 'subareaID': '278', 'subareaName': 'Meerapur', 'assignedSE': 'SS-1131'});
databaseRef.child('279').set({'regionId': '3', 'areaID': '8', 'subareaID': '279', 'subareaName': 'Nirala Nagar', 'assignedSE': 'SS-1131'});
databaseRef.child('280').set({'regionId': '3', 'areaID': '8', 'subareaID': '280', 'subareaName': 'Karelabagh', 'assignedSE': 'SS-1131'});
databaseRef.child('281').set({'regionId': '3', 'areaID': '8', 'subareaID': '281', 'subareaName': 'Kareli', 'assignedSE': 'SS-1131'});
databaseRef.child('282').set({'regionId': '3', 'areaID': '8', 'subareaID': '282', 'subareaName': 'Dariyabad', 'assignedSE': 'SS-1131'});
databaseRef.child('283').set({'regionId': '3', 'areaID': '8', 'subareaID': '283', 'subareaName': 'Malviya Nagar', 'assignedSE': 'SS-1131'});
databaseRef.child('284').set({'regionId': '3', 'areaID': '8', 'subareaID': '284', 'subareaName': 'Bahadurganj', 'assignedSE': 'SS-1131'});
databaseRef.child('285').set({'regionId': '3', 'areaID': '8', 'subareaID': '285', 'subareaName': 'Malviya Road', 'assignedSE': 'SS-1131'});
databaseRef.child('286').set({'regionId': '3', 'areaID': '8', 'subareaID': '286', 'subareaName': 'Shahganj', 'assignedSE': 'SS-1131'});
databaseRef.child('287').set({'regionId': '3', 'areaID': '8', 'subareaID': '287', 'subareaName': 'Badshahi Mandi', 'assignedSE': 'SS-1131'});
databaseRef.child('288').set({'regionId': '3', 'areaID': '8', 'subareaID': '288', 'subareaName': 'Kalyani Devi', 'assignedSE': 'SS-1131'});
databaseRef.child('289').set({'regionId': '3', 'areaID': '8', 'subareaID': '289', 'subareaName': 'Nakhas Kona', 'assignedSE': 'SS-1131'});
databaseRef.child('290').set({'regionId': '3', 'areaID': '8', 'subareaID': '290', 'subareaName': 'Tharwai', 'assignedSE': 'UU-0001'});
databaseRef.child('291').set({'regionId': '3', 'areaID': '8', 'subareaID': '291', 'subareaName': 'govindpur', 'assignedSE': 'UU-0001'});
databaseRef.child('292').set({'regionId': '3', 'areaID': '8', 'subareaID': '292', 'subareaName': 'Phaphamau', 'assignedSE': 'UU-0001'});
databaseRef.child('293').set({'regionId': '3', 'areaID': '8', 'subareaID': '293', 'subareaName': 'Saraon', 'assignedSE': 'UU-0001'});
databaseRef.child('294').set({'regionId': '3', 'areaID': '8', 'subareaID': '294', 'subareaName': 'Teliarganj', 'assignedSE': 'UU-0001'});
databaseRef.child('295').set({'regionId': '3', 'areaID': '8', 'subareaID': '295', 'subareaName': 'Mumfordganj', 'assignedSE': 'UU-0001'});
databaseRef.child('296').set({'regionId': '3', 'areaID': '8', 'subareaID': '296', 'subareaName': 'Atrapmpur', 'assignedSE': 'UU-0001'});
databaseRef.child('297').set({'regionId': '3', 'areaID': '8', 'subareaID': '297', 'subareaName': 'Shantipuram', 'assignedSE': 'UU-0001'});
databaseRef.child('298').set({'regionId': '3', 'areaID': '8', 'subareaID': '298', 'subareaName': 'Katra', 'assignedSE': 'UU-0001'});
databaseRef.child('299').set({'regionId': '3', 'areaID': '8', 'subareaID': '299', 'subareaName': 'Alopibagh', 'assignedSE': 'UU-0001'});
databaseRef.child('300').set({'regionId': '3', 'areaID': '8', 'subareaID': '300', 'subareaName': 'Daraganj', 'assignedSE': 'UU-0001'});
databaseRef.child('301').set({'regionId': '3', 'areaID': '8', 'subareaID': '301', 'subareaName': 'Allahpur', 'assignedSE': 'UU-0001'});
databaseRef.child('302').set({'regionId': '3', 'areaID': '8', 'subareaID': '302', 'subareaName': 'Lajpat Rai Road', 'assignedSE': 'UU-0001'});
databaseRef.child('303').set({'regionId': '3', 'areaID': '8', 'subareaID': '303', 'subareaName': 'Mugarsan', 'assignedSE': 'UU-0001'});
databaseRef.child('304').set({'regionId': '3', 'areaID': '8', 'subareaID': '304', 'subareaName': 'Hanumanganj', 'assignedSE': 'UU-0001'});
databaseRef.child('305').set({'regionId': '3', 'areaID': '8', 'subareaID': '305', 'subareaName': 'Chhatnang', 'assignedSE': 'UU-0001'});
databaseRef.child('306').set({'regionId': '3', 'areaID': '8', 'subareaID': '306', 'subareaName': 'Sarai Inayat', 'assignedSE': 'UU-0001'});
databaseRef.child('307').set({'regionId': '3', 'areaID': '8', 'subareaID': '307', 'subareaName': 'Bahadurpur', 'assignedSE': 'UU-0001'});
databaseRef.child('308').set({'regionId': '3', 'areaID': '8', 'subareaID': '308', 'subareaName': 'Handia', 'assignedSE': 'UU-0001'});
databaseRef.child('309').set({'regionId': '3', 'areaID': '8', 'subareaID': '309', 'subareaName': 'balipur', 'assignedSE': 'UU-0001'});
databaseRef.child('310').set({'regionId': '3', 'areaID': '8', 'subareaID': '310', 'subareaName': 'Trivenipuram', 'assignedSE': 'UU-0001'});
databaseRef.child('311').set({'regionId': '3', 'areaID': '8', 'subareaID': '311', 'subareaName': 'Bani', 'assignedSE': 'UU-0001'});
databaseRef.child('312').set({'regionId': '3', 'areaID': '8', 'subareaID': '312', 'subareaName': 'Jalalpur', 'assignedSE': 'UU-0001'});
databaseRef.child('313').set({'regionId': '3', 'areaID': '8', 'subareaID': '313', 'subareaName': 'Barethi', 'assignedSE': 'UU-0001'});
databaseRef.child('314').set({'regionId': '3', 'areaID': '8', 'subareaID': '314', 'subareaName': 'Fatua', 'assignedSE': 'UU-0001'});
databaseRef.child('315').set({'regionId': '3', 'areaID': '8', 'subareaID': '315', 'subareaName': 'Jhunsi', 'assignedSE': 'UU-0001'});
databaseRef.child('316').set({'regionId': '3', 'areaID': '8', 'subareaID': '316', 'subareaName': 'Andawa', 'assignedSE': 'UU-0001'});
databaseRef.child('317').set({'regionId': '3', 'areaID': '8', 'subareaID': '317', 'subareaName': 'Kotwa', 'assignedSE': 'UU-0001'});
databaseRef.child('318').set({'regionId': '3', 'areaID': '8', 'subareaID': '318', 'subareaName': 'Lal Chowk', 'assignedSE': 'UU-0001'});
databaseRef.child('319').set({'regionId': '3', 'areaID': '8', 'subareaID': '319', 'subareaName': 'Garapur', 'assignedSE': 'UU-0001'});
databaseRef.child('320').set({'regionId': '3', 'areaID': '8', 'subareaID': '320', 'subareaName': 'Rahimanpur', 'assignedSE': 'UU-0001'});
databaseRef.child('321').set({'regionId': '3', 'areaID': '8', 'subareaID': '321', 'subareaName': 'Sahson', 'assignedSE': 'UU-0001'});
databaseRef.child('322').set({'regionId': '3', 'areaID': '8', 'subareaID': '322', 'subareaName': 'Gomati', 'assignedSE': 'UU-0001'});
databaseRef.child('323').set({'regionId': '3', 'areaID': '8', 'subareaID': '323', 'subareaName': 'Hetapatti', 'assignedSE': 'UU-0001'});
databaseRef.child('324').set({'regionId': '3', 'areaID': '8', 'subareaID': '324', 'subareaName': 'Phulpur', 'assignedSE': 'UU-0001'});
databaseRef.child('325').set({'regionId': '3', 'areaID': '8', 'subareaID': '325', 'subareaName': 'Mehawa', 'assignedSE': 'UU-0001'});
databaseRef.child('326').set({'regionId': '3', 'areaID': '8', 'subareaID': '326', 'subareaName': 'Rassoolabad', 'assignedSE': 'UU-0001'});
databaseRef.child('327').set({'regionId': '3', 'areaID': '8', 'subareaID': '327', 'subareaName': 'Mehdauri Colony', 'assignedSE': 'UU-0001'});
databaseRef.child('328').set({'regionId': '3', 'areaID': '8', 'subareaID': '328', 'subareaName': 'Kalindipuram Housing', 'assignedSE': 'SS-1132'});
databaseRef.child('329').set({'regionId': '3', 'areaID': '8', 'subareaID': '329', 'subareaName': 'Chota Baghara', 'assignedSE': 'UU-0001'});
databaseRef.child('330').set({'regionId': '3', 'areaID': '8', 'subareaID': '330', 'subareaName': 'Balrampur House', 'assignedSE': 'UU-0001'});
databaseRef.child('331').set({'regionId': '3', 'areaID': '8', 'subareaID': '331', 'subareaName': 'Salori', 'assignedSE': 'UU-0001'});
databaseRef.child('332').set({'regionId': '3', 'areaID': '8', 'subareaID': '332', 'subareaName': 'Om Gayatri Nagar', 'assignedSE': 'UU-0001'});
databaseRef.child('333').set({'regionId': '3', 'areaID': '8', 'subareaID': '333', 'subareaName': 'Transport Nagar', 'assignedSE': 'SS-1132'});
databaseRef.child('334').set({'regionId': '3', 'areaID': '8', 'subareaID': '334', 'subareaName': 'Mundera', 'assignedSE': 'SS-1132'});
databaseRef.child('335').set({'regionId': '3', 'areaID': '8', 'subareaID': '335', 'subareaName': 'Preetam Nagar', 'assignedSE': 'SS-1132'});
databaseRef.child('336').set({'regionId': '3', 'areaID': '8', 'subareaID': '336', 'subareaName': 'Lukerganj', 'assignedSE': 'SS-1132'});
databaseRef.child('337').set({'regionId': '3', 'areaID': '8', 'subareaID': '337', 'subareaName': 'Bamrauli', 'assignedSE': 'SS-1132'});
databaseRef.child('338').set({'regionId': '3', 'areaID': '8', 'subareaID': '338', 'subareaName': 'GTB Nagar', 'assignedSE': 'SS-1132'});
databaseRef.child('339').set({'regionId': '3', 'areaID': '8', 'subareaID': '339', 'subareaName': 'Chauphatka', 'assignedSE': 'SS-1132'});
databaseRef.child('340').set({'regionId': '3', 'areaID': '8', 'subareaID': '340', 'subareaName': 'Jhalwa', 'assignedSE': 'SS-1132'});
databaseRef.child('341').set({'regionId': '3', 'areaID': '8', 'subareaID': '341', 'subareaName': 'Subedarganj', 'assignedSE': 'SS-1132'});
databaseRef.child('342').set({'regionId': '3', 'areaID': '8', 'subareaID': '342', 'subareaName': 'Raurooppur', 'assignedSE': 'SS-1132'});
databaseRef.child('343').set({'regionId': '3', 'areaID': '8', 'subareaID': '343', 'subareaName': 'Rajrooppur', 'assignedSE': 'SS-1132'});
databaseRef.child('344').set({'regionId': '3', 'areaID': '8', 'subareaID': '344', 'subareaName': 'Kendranchal Begum Sarai', 'assignedSE': 'SS-1132'});
databaseRef.child('345').set({'regionId': '3', 'areaID': '8', 'subareaID': '345', 'subareaName': 'Beniganj', 'assignedSE': 'SS-1132'});
databaseRef.child('346').set({'regionId': '3', 'areaID': '8', 'subareaID': '346', 'subareaName': 'Sulem Sarai', 'assignedSE': 'SS-1132'});
databaseRef.child('347').set({'regionId': '3', 'areaID': '8', 'subareaID': '347', 'subareaName': 'Dhoomanganj', 'assignedSE': 'SS-1132'});
databaseRef.child('348').set({'regionId': '3', 'areaID': '8', 'subareaID': '348', 'subareaName': 'Unknown SubArea', 'assignedSE': 'UU-0001'});
}
